name: Train WMI Repo

on:
  workflow_dispatch:
    inputs:
      epochs:
        description: "Number of epochs"
        required: true
        default: "10"

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Clone WMI repo
        run: |
          git clone https://oauth2:${{ secrets.WMI_TOKEN }}@git.wmi.amu.edu.pl/s481839/InzynieriaUczeniaMaszynowego.git repo

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install torch pandas numpy scikit-learn joblib mlflow==2.12.1

      - name: Train
        working-directory: repo
        run: |
          python src/torchtrain.py

      - name: Predict
        working-directory: repo
        run: |
          python src/torchpredict.py
